/* ============================================================================
   asset-sizes.mjs  —  print an `assetSizes` block for story.js
   ----------------------------------------------------------------------------
   The preloader does NOT need this. It finds every file from story.js on its
   own and learns each real size from the server's Content-Length header. This
   script only front-loads those numbers so the loading bar is perfectly smooth
   from the very first frame instead of settling over the first moment.

   Run it from the template folder (the one holding index.html):

       node tools/asset-sizes.mjs

   Then paste the printed block into story.js, replacing the commented-out
   `assetSizes` example. Re-run it whenever you swap or re-encode a file.
   ============================================================================ */
import { readdir, stat } from "node:fs/promises";
import { join, posix } from "node:path";

const FOLDERS = ["pages", "sfx"];
const MEDIA = /\.(webm|mp4|webp|png|jpe?g|ogg|mp3|m4a|wav)$/i;

const rows = [];
for (const dir of FOLDERS) {
  let names;
  try {
    names = await readdir(dir);
  } catch {
    console.error(`(skipped ${dir}/ — no such folder here; run this from the ` +
                  `folder that holds index.html)`);
    continue;
  }
  for (const name of names.sort()) {
    if (!MEDIA.test(name)) continue;                 // ignore READMEs, notes, etc.
    const full = join(dir, name);
    const info = await stat(full);
    if (!info.isFile()) continue;                    // don't walk subfolders
    rows.push({ url: posix.join(dir, name), bytes: info.size });
  }
}

if (!rows.length) {
  console.error("No media found in pages/ or sfx/ — nothing to do.");
  process.exit(1);
}

rows.sort((a, b) => a.bytes - b.bytes);
const pad = Math.max(...rows.map(r => r.url.length)) + 3;
const total = rows.reduce((n, r) => n + r.bytes, 0);

console.log("  /* Generated by tools/asset-sizes.mjs — paste into story.js. */");
console.log("  assetSizes: {");
rows.forEach((r, i) => {
  const key = `"${r.url}":`;
  const comma = i === rows.length - 1 ? "" : ",";
  console.log(`    ${key.padEnd(pad)}${String(r.bytes).padStart(9)}${comma}`);
});
console.log("  },");
console.log(`\n  // ${rows.length} files, ${(total / 1048576).toFixed(1)} MB total ` +
            `— this is what a first-time reader downloads before Play appears.`);
